# Generated by Django 5.1.7 on 2025-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedmatrix',
            name='name',
        ),
        migrations.RemoveField(
            model_name='detailedmatrix',
            name='value',
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='class_name',
            field=models.CharField(db_column='class', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='description',
            field=models.TextField(db_column='Intervention Description', null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='high_cost',
            field=models.FloatField(db_column='High Cost.1', null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='impact_rating',
            field=models.FloatField(db_column='Impact Rating', null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='intervention',
            field=models.CharField(db_column='Interventions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='low_cost',
            field=models.FloatField(db_column='Low Cost.1', null=True),
        ),
        migrations.AddField(
            model_name='detailedmatrix',
            name='theme',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='detailedmatrix',
            table='DetailedMatrix',
        ),
    ]
