# Generated by Django 5.1.7 on 2025-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_detailedmatrix_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTargets',
            fields=[
                ('class_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target_rating', models.FloatField()),
            ],
            options={
                'db_table': 'ClassTargets',
            },
        ),
    ]
