# Generated by Django 5.1.7 on 2025-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_classtargets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='class', max_length=100, null=True)),
                ('theme', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Interventions',
            },
        ),
    ]
