# Generated by Django 5.1.7 on 2025-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_interventions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='DetailedMatrix',
        ),
    ]
