# Generated by Django 5.1.7 on 2025-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_delete_detailedmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventions',
            name='cost_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interventions',
            name='cost_range',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
