# Generated by Django 5.1.7 on 2025-09-11 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_delete_detailedmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('high-contrast', 'High Contrast')], default='light', max_length=15)),
                ('text_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('x-large', 'Extra Large')], default='normal', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
