# Generated by Django 5.1.7 on 2025-09-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_interventions_cost_level_interventions_cost_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=120, null=True)),
                ('building_type', models.CharField(blank=True, max_length=120, null=True)),
                ('roof_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roof_percent_gifa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('basement_present', models.BooleanField(default=False)),
                ('basement_size_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('basement_percent_gifa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('num_apartments', models.PositiveIntegerField(blank=True, null=True)),
                ('num_keys', models.PositiveIntegerField(blank=True, null=True)),
                ('num_wcs', models.PositiveIntegerField(blank=True, null=True)),
                ('gifa_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='GIFA (m²)')),
                ('external_wall_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_openings_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('building_footprint_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_auto_budget_aud', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='app1.user')),
            ],
            options={
                'db_table': 'Metrics',
                'indexes': [models.Index(fields=['building_type'], name='Metrics_buildin_21e2d0_idx'), models.Index(fields=['project_code'], name='Metrics_project_c77f1d_idx'), models.Index(fields=['created_at'], name='Metrics_created_d151a3_idx')],
            },
        ),
    ]
