# Generated by Django 5.1.7 on 2025-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventions',
            name='intervention_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
