# Generated by Django 5.1.7 on 2025-09-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile'),
        ('app1', '0008_interventions_intervention_rating'),
    ]

    operations = [
    ]
