# Generated by Django 5.1.7 on 2025-09-15 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_interventions_intervention_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metrics',
            name='Metrics_buildin_21e2d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='metrics',
            name='Metrics_project_c77f1d_idx',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='project_code',
        ),
        migrations.AddField(
            model_name='metrics',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='project_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='project_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['user'], name='Metrics_user_id_2fde8c_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['project_id'], name='Metrics_project_0ad15f_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['project_type'], name='Metrics_project_1d8046_idx'),
        ),
    ]
