# Generated by Django 5.1.7 on 2025-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_metrics_metrics_buildin_21e2d0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventions',
            name='impact_rating',
            field=models.IntegerField(blank=True, help_text='1–5 (from Excel Impact Rating)', null=True),
        ),
    ]
