# Generated by Django 5.1.7 on 2025-10-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_interventions_impact_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventions',
            name='impact_rating',
        ),
        migrations.CreateModel(
            name='InterventionDependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interventions')),
            ],
            options={
                'db_table': 'intervention_dependencies',
            },
        ),
    ]
