# Generated by Django 5.1.7 on 2025-10-01 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_interventions_impact_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventions',
            name='impact_rating',
        ),
        migrations.CreateModel(
            name='MetricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=80)),
                ('operator', models.CharField(max_length=8)),
                ('value', models.CharField(max_length=120)),
                ('weight', models.FloatField(default=1.0)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app1.interventions')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_as', to='app1.interventions')),
                ('B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_bs', to='app1.interventions')),
            ],
            options={
                'unique_together': {('A', 'B')},
            },
        ),
    ]
