# Generated by Django 5.1.7 on 2025-10-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_interventions_impact_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventiondependencies',
            options={'managed': False},
        ),
    ]
