# Generated by Django 5.1.7 on 2025-10-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_interventiondependencies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='intervention_effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_value', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('source_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_effects', to='app1.interventions')),
                ('target_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_effects', to='app1.interventions')),
            ],
        ),
    ]
