# Generated by Django 5.1.7 on 2025-10-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_interventiondependencies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('eq', '=='), ('neq', '!='), ('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('in', 'in'), ('nin', 'not in'), ('true', 'is True'), ('false', 'is False'), ('empty', 'is empty'), ('nempty', 'not empty'), ('contains', 'str contains'), ('ncontains', 'str not contains')], max_length=12)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app1.interventions')),
            ],
            options={
                'indexes': [models.Index(fields=['intervention', 'field_name'], name='app1_metric_interve_491bae_idx')],
            },
        ),
    ]
