# Generated by Django 5.1.7 on 2025-10-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_metricrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interventions')),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app1.metrics')),
            ],
            options={
                'db_table': 'MetricsSelection',
                'unique_together': {('metrics', 'intervention')},
            },
        ),
    ]
