# Generated by Django 5.1.7 on 2025-10-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_intervention_effects'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_intervention_name', models.CharField(db_column='source_intervention_name', max_length=255)),
                ('target_intervention_name', models.CharField(db_column='target_intervention_name', max_length=255)),
                ('effect_value', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intervention_effects',
            },
        ),
        migrations.RemoveField(
            model_name='intervention_effects',
            name='source_intervention',
        ),
        migrations.RemoveField(
            model_name='intervention_effects',
            name='target_intervention',
        ),
        migrations.RemoveIndex(
            model_name='metrics',
            name='Metrics_user_id_2fde8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='metrics',
            name='Metrics_project_0ad15f_idx',
        ),
        migrations.RemoveIndex(
            model_name='metrics',
            name='Metrics_project_1d8046_idx',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='project_type',
        ),
        migrations.AddField(
            model_name='metrics',
            name='project_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='app1.user'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['building_type'], name='Metrics_buildin_21e2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['project_code'], name='Metrics_project_c77f1d_idx'),
        ),
        migrations.DeleteModel(
            name='intervention_effects',
        ),
    ]
