# Generated by Django 5.1.7 on 2025-10-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_interventioneffects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='estimated_auto_budget_aud',
            new_name='total_budget_aud',
        ),
    ]
