# Generated by Django 5.1.7 on 2025-10-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_estimated_auto_budget_aud_metrics_total_budget_aud'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='last_selection_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='selected_intervention_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
