# Generated by Django 5.1.7 on 2025-10-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_metrics_last_selection_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='last_selection_at',
        ),
    ]
