# Generated by Django 5.1.7 on 2025-10-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_metrics_last_selection_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app1.interventions')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_selections', to='app1.metrics')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user')),
            ],
            options={
                'db_table': 'InterventionSelection',
                'unique_together': {('project', 'intervention')},
            },
        ),
    ]
